//
// Created by Ladislav Lisy on 10.04.16.
// Copyright (c) 2016 ___FULLUSERNAME___. All rights reserved.
//

import Foundation

public enum ConfigArticleCode : Int
{
    case ARTICLE_UNKNOWN = 0
    case ARTICLE_CONTRACT_EMPL_TERM = 101
    case ARTICLE_POSITION_EMPL_TERM = 110
    case ARTICLE_INCOME_GROSS = 501
    case ARTICLE_INCOME_NETTO = 502
    case ARTICLE_CONTRACT_STAT_TERM = 102
    case ARTICLE_CONTRACT_WORK_TERM = 103
    case ARTICLE_CONTRACT_TASK_TERM = 104
    case ARTICLE_SCHEDULE_WORK = 201
    case ARTICLE_SALARY_BASE = 202
    case ARTICLE_TIMESHEET_SCHEDULE = 251
    case ARTICLE_TIMESHEET_WORKING = 252
    case ARTICLE_TIMESHEET_ABSENCE = 253
    case ARTICLE_TIMEHOURS_WORKING = 254
    case ARTICLE_TIMEHOURS_ABSENCE = 255
    case ARTICLE_HEALTH_INCOME_SUBJECT = 301
    case ARTICLE_SOCIAL_INCOME_SUBJECT = 302
    case ARTICLE_GARANT_INCOME_SUBJECT = 303
    case ARTICLE_HEALTH_INCOME_PARTICIP = 305
    case ARTICLE_SOCIAL_INCOME_PARTICIP = 306
    case ARTICLE_GARANT_INCOME_PARTICIP = 307
    case ARTICLE_HEALTH_BASIS_GENERAL = 311
    case ARTICLE_HEALTH_BASIS_MANDATORY = 312
    case ARTICLE_HEALTH_BASIS_LEGALCAP = 313
    case ARTICLE_SOCIAL_BASIS_GENERAL = 321
    case ARTICLE_SOCIAL_BASIS_PENSION = 322
    case ARTICLE_SOCIAL_BASIS_LEGALCAP = 323
    case ARTICLE_GARANT_BASIS_PENSION = 331
    case ARTICLE_GARANT_BASIS_LEGALCAP = 332
    case ARTICLE_HEALTH_EMPLOYEE_GENERAL = 341
    case ARTICLE_HEALTH_EMPLOYEE_MANDATORY = 342
    case ARTICLE_SOCIAL_EMPLOYEE_GENERAL = 351
    case ARTICLE_SOCIAL_EMPLOYEE_PENSION = 352
    case ARTICLE_GARANT_EMPLOYEE_PENSION = 361
    case ARTICLE_HEALTH_EMPLOYER_GEENRAL = 371
    case ARTICLE_HEALTH_EMPLOYER_MANDATORY = 372
    case ARTICLE_SOCIAL_EMPLOYER_GENERAL = 373
    case ARTICLE_TAXING_INCOME_SUBJECT = 401
    case ARTICLE_TAXING_INCOME_HEALTH = 402
    case ARTICLE_TAXING_INCOME_SOCIAL = 403
    case ARTICLE_TAXING_ADVANCES_INCOME = 411
    case ARTICLE_TAXING_ADVANCES_HEALTH = 412
    case ARTICLE_TAXING_ADVANCES_SOCIAL = 413
    case ARTICLE_TAXING_ADVANCES_BASIS_GENERAL = 414
    case ARTICLE_TAXING_ADVANCES_BASIS_SOLIDARY = 415
    case ARTICLE_TAXING_ADVANCES_GENERAL = 416
    case ARTICLE_TAXING_ADVANCES_SOLIDARY = 417
    case ARTICLE_TAXING_ADVANCES_TOTAL = 418
    case ARTICLE_TAXING_ALLOWANCE_PAYER = 421
    case ARTICLE_TAXING_ALLOWANCE_CHILD = 422
    case ARTICLE_TAXING_ALLOWANCE_DISABILITY = 423
    case ARTICLE_TAXING_ALLOWANCE_STUDYING = 424
    case ARTICLE_TAXING_REBATE_PAYER = 431
    case ARTICLE_TAXING_REBATE_CHILD = 432
    case ARTICLE_TAXING_BONUS_CHILD = 433
    case ARTICLE_TAXING_WITHHOLD_INCOME = 451
    case ARTICLE_TAXING_WITHHOLD_HEALTH = 452
    case ARTICLE_TAXING_WITHHOLD_SOCIAL = 453
    case ARTICLE_TAXING_WITHHOLD_BASIS_GENERAL = 454
    case ARTICLE_TAXING_WITHHOLD_GENERAL = 456
}

public enum ProcessCategory : Int
{
    case CATEGORY_TERMS  = 0
    case CATEGORY_START  = 1
    case CATEGORY_TIMES  = 2
    case CATEGORY_AMOUNT = 3
    case CATEGORY_GROSS  = 4
    case CATEGORY_NETTO  = 5
    case CATEGORY_FINAL  = 9
}

